### ISSUE TITLE
LS Review

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#505]
**Investigate**
- [x]  We have 2,500 fewer **MOEO** records.  There are fewer records in the following subgroups: Health promotion, disease prevention, etc.  Why the decrease?
> We now pull MOEO data from Open Data in [this script](https://github.com/NYCPlanning/db-data-library/blob/main/library/script/moeo_socialservicesitelocations.py). As of the 20210414 version, there are only 671 records in the raw data.

**Investigate and fix**
- [x] **Government offices** - it looks like we got too aggressive with deduplication.  For example for 66 John street we went from 8 records with different agencies in the previous version of FacDB to 3 records with different facility types in the current version.  If deduplication is causing the drop in the number of records change the deduplication logic.
> It looks like this is a result of our deduplication logic, combined with a vague facname for the office building at 66 John Street. We're deduplicating records with the same bin or geom, facname, factype, and datasource where as follows:
https://github.com/NYCPlanning/db-facilities/blob/f1d4194bbc4c414c0d9798f6ac08ebc83e135635/facdb/sql/_deduplication.sql#L5-L18
For the dcp_colp records at 66 John Street, all records have facname of "Office Bldg" and so several meet this criteria. Would it be better to correct parcel names for dcp_colp, or to change the within-source deduplication logic for all data sources?

It looks like [this logic](https://github.com/NYCPlanning/db-facilities/blob/7021a313caaabf2577d3f934cfceb56d3f470b4e/facdb/sql/dcp_colp.sql#L454) is causing the drop in government offices because there are only 3 66 JOHN STREET records in `_dcp_colp`
Question for LS: To get all records into facdb and avoid building a special workaround in several places for COLP should we append ` - opabbrev` to the facname if the facname is `OFFICE BLDG`?
Yes, add opabbrev.

- [x] **Charter schools** - there is drop when switching to just LCGMS as a source.  If NYSED charter school records are not in the LCGMS dataset, then add back in charter schools from NYSED and dedupe between NYSED and LCGMS for charter and pre schools. This impacts facsubgrps CHARTER K-12 SCHOOLS and PRESCHOOLS FOR CHILDREN WITH DISABILITIES
> We currently delete all charter schools from NYSED.
https://github.com/NYCPlanning/db-facilities/blob/0c1102190c18b4a8cc9802449ce42a81d1644dbf/facdb/sql/nysed_activeinstitutions.sql#L141-L144
If we need only delete charter schools when they appear in LCGMS, what fields should we join on?
```sql
SELECT 
a.popular_name,
b.location_name
FROM nysed_activeinstitutions a
JOIN doe_lcgms b
ON UPPER(regexp_replace(a.popular_name, '[^a-zA-Z0-9]+', '','g'))=UPPER(regexp_replace(b.location_name, '[^a-zA-Z0-9]+', '','g'))
WHERE a.inst_sub_type_description LIKE '%CHARTER SCHOOL%';
```

> finds 84 exact matches.

I think that there needs to be some location component included because some matches are in different places (i.e. Kings Collegiate Charter School on 905 WINTHROP ST vs 1084 LENOX ROAD), so maybe the workflow is this:
1) Don't filter out charter schools from nysed_activeinstitutions
2) Add a deduplication step between between `nysed_activeinstitutions` and `doe_lcgms`
Keep the `doe_lcgms` record
Duplicates are when there is a match between a `nysed_activeinstitutions` and `doe_lcgms` record where the facsubgrp='Charter K-12 Schools' and the facnames match and the locations match
```
UPPER(regexp_replace(a.facname, '[^a-zA-Z0-9]+', '','g'))=UPPER(regexp_replace(b.facname, '[^a-zA-Z0-9]+', '','g'))
AND a. facsubgrp='Charter K-12 Schools' AND b. facsubgrp='Charter K-12 Schools'
AND (a.bin=b.bin OR a.geom=b.geom OR a.address=b.addess OR a.bbl=b.bbl)
```
Yes
Triple check that not in LCGMS

- [x] Dropped 2 **fire stations** with this version.  We need to capture all fire stations.
> In `_fdny_firehouses`, two records are missing geometries. They have special characters in the address fields: 489-91 Saint Johnï¿½s Place and 1352 Saint Johnï¿½s Place. We need to clean these before geocoding. #507 
- [x] **DPR** - do not delete records that are undeveloped, should be under parks and open space. 
> The undeveloped records should be Miscellaneous Use in the current logic. Should we change this facsubgrp to something specific to parks?
https://github.com/NYCPlanning/db-facilities/blob/f1d4194bbc4c414c0d9798f6ac08ebc83e135635/facdb/sql/dpr_parksproperties.sql#L17-L19
We currently don't have a Parks version of Miscellaneous Use in the classification lookup
https://github.com/NYCPlanning/db-facilities/blob/develop/facdb/data/lookup_classification.csv#L79

Undeveloped factype and subgroup and map to Parks and Plazas

**Small fixes**
- [x] Remove leading / extra blanks in factype #508 
- [x] Remove leading / extra blanks in address and street name #508 
- [x] FGDB - needs to be projected to state plane #506

**Documentation**
- [x] Move FacDB ReadMe off Docs site and into Word on SharePoint
- [ ] #509

**Comment by AmandaDoyle** [comment]
@mgraber The fix for fire stations isn't showing up in the latest version.

**Comment by AmandaDoyle** [comment]
- There are 585 records where `facsubgrp = 'CHARTER K-12 SCHOOLS'` in the new version of FacDB, compared to 265 in the version I sent on 6/21
- There are 97 records where `facsubgrp = 'PRESCHOOLS FOR STUDENTS WITH DISABILITIES'`, which is the same as what I sent on 6/21 because this subgroup is only assigned to records that come from `nysed_activeinstitutions`

- There are 365 records where facsubgrp = `CITY GOVERNMENT AGENCIES`
1 Centre Street
We are removing duplicates between 'Office' and 'Agency Office' that shared the same BBL - see [here](https://github.com/NYCPlanning/db-facilities/blob/develop/facdb/sql/dcp_colp.sql#L531).  This goes back to the intent of FacDB.  Is it meant to show that there is an agency office on that lot, or to show the agencies that have an office in that lot?  Right now, we're showing a mix because of conflicting decisions.

253 Broadway
Records are being deduped with [this logic](https://github.com/NYCPlanning/db-facilities/blob/cb6abd720697b4f71fc36f5f461ae238853095b3/facdb/sql/dcp_colp.sql#L545)

Should we either A) add operating agency to deduplication logic? and remove the operating agency from facname where facname is 'OFFICE BLDG'? OR B) add the operating agency to all facnames that are like office?

**Comment by AmandaDoyle** [comment]
LAS - decided to add operating agency to deduplication logic and remove the operating agency from facname
